### ISSUE TITLE
Refactor: Commonalities between set-implementations

### ISSUE THREAD

**Issue by peterzeller** [SyncFree/antidote_crdt#10]
Currenty the add-wins and remove-wins set both use a similar function for `create_downstreams` and `apply_downstreams`. I think what we need is a function similar to [orddict:merge](http://erlang.org/doc/man/orddict.html#merge-3). However, the function in merge only is invoked, when an entry exists in both dicts. We would need a variant that is also called for the other cases.

I think if we have such a function both modules could be written in a nicer way.
I am also open to other ideas to extract the common code into some common module.

@gyounes @vitorenesduarte do you want to work on this?

**Comment by albsch** [comment]
Please reopen if still valid at https://github.com/AntidoteDB/antidote
