### ISSUE TITLE
Implement compression functions for the remaining data types

### ISSUE THREAD

**Issue by gmcabrita** [SyncFree/antidote_crdt#19]
Pull request #18 implemented compression for a majority of data types, but a few are still missing:
- [ ] antidote_crdt_bcounter
- [ ] antidote_crdt_map_aw
- [ ] antidote_crdt_map_rr
- [ ] antidote_crdt_rga

**Comment by albsch** [comment]
Please reopen if still valid at https://github.com/AntidoteDB/antidote
