### ISSUE TITLE
Underperforming RGArray implementation

### ISSUE THREAD

**Issue by Horusiath** [SyncFree/antidote_crdt#20]
I've taken a look at the rga implementation and I've noticed that it has been implemented using Erlang list. Example implementation of [add_element](https://github.com/SyncFree/antidote_crdt/blob/3ea9ad0f45ecb4e3eea04ccf7d095b671bf64ff0/src/antidote_crdt_rga.erl#L119) can recreate the entire list on every insert. Finding an element is potentially O(N) operation (however I understand that in most obvious use cases elements will be appended to the end, making it optimistically O(1)).

Also I've noticed that rga is not mentioned in official AntidoteDB docs. Therefore my question is: what's the status of this data structure?

**Comment by bieniusa** [comment]
I totally agree: The implementation of RGA has quite a few flaws. This is also why we didn't include it into the documentation, yet, as we rather not have people using it in production.

We have been working on some alternative designs for sequence CRDTs. @peterzeller has more information on that.

**Comment by Horusiath** [comment]
That's interesting. Also I've seen that rga has cleaning method, but it's essentially removing all tombstoned elements, which makes quite hard to find a correct point in time to actually call it from different replica sets. I'm working over RG array implementation on another platform, which implements tombstones as vector clocks - to allow pruning of elements before given point in time (ideally the lowest stable version vector).

But since you've said that you're working on other design, I'd love to hear more about it. Is it a redesigned rga, a new CRDT like lseq or are you coming up with something totally new?

**Comment by peterzeller** [comment]
I think the current RGA implementation in our library does not work correctly. At least it is not well tested and therefore not available in Antidote.

We have another implementation of RGA and an implementation of Treedoc which are the result of a Bachelor thesis. 
The implementation is very close to the pseudo-code description in the respective papers, so I am more confident that they are correct.
However, as a result performance was not very good, so we did not include it in the library yet.

I think @gyounes was working on another list CRDT design.

**Comment by marc-shapiro** [comment]
For those interested in RGA, I suggest implementing RGA-Split, which is specifically designed for text editing. 
https://pages.lip6.fr/Marc.Shapiro/papers/rgasplit-group2016-11.pdf
http://dx.doi.org/10.1145/2957276.2957300

                        Marc

**Comment by albsch** [comment]
Please reopen if still valid at https://github.com/AntidoteDB/antidote
