### ISSUE TITLE
Type refactoring

### ISSUE THREAD

**Issue by bieniusa** [SyncFree/antidote_crdt#23]
The type definitions in include/antidote_crdt.hrl are not very helpful.

I suggest the following common naming conventions:
- The upstream operation (op()) is a tuple of an atom (operation name) and tuple (parameters).
- The downstream operation (effect()) is just a tuple with CRDT-specific structure.

Many CRDTs follow this convention already, some using CRDT name prefixes, some are doing very different things. We need to unify that.

Further, it would be helpful to export these types as an opaque type in the header file.

**Comment by marc-shapiro** [comment]
> Le 25 avr. 2018 à 17:44, Annette Bieniusa <notifications@github.com> a écrit :
> 
> The type definitions in include/antidote_crdt.hrl are not very helpful.
> 
> I suggest the following common naming conventions:
> 
> The upstream operation (op()) is a tuple of an atom (operation name) and tuple (parameters).

Two levels of tuple are overkill, isn't it?  A single-level tuple containing operation name and arguments should be enough.

						Marc

PS s/parameters/arguments/

**Comment by bieniusa** [comment]
The number of parameters differs between operations. Arbitrary length tuples are nasty to handle because you cannot use pattern matching on them.

**Comment by peterzeller** [comment]
Using `opaque` in a header file has no effect afaik -- `opaque` only works on the module level when using exported types from different modules. 

I would keep the definitions of the types as they are now. Changing the effect of the counter CRDT from  a single integer to an integer wrapped in a tuple does not really help anyone.

I think there is no sane way to use Dialyzer for this library. That would need type parameters for behavior specifications, or existential types, or some other feature that Dialyzer does not have.

**Comment by bieniusa** [comment]
I don't want to use the unified naming scheme for the sake of Dialyzer, but for documentation purpose.
Right now we have effect, downstream_effect, downstream_op, with and without CRDT name prefix....
This makes it very hard to navigate the different files.

Agreed: The params part does not need to be a tuple, it can be an arbitrary term.

**Comment by albsch** [comment]
Please reopen if still valid at https://github.com/AntidoteDB/antidote
