### ISSUE TITLE
Sequence CRDTs

### ISSUE THREAD

**Issue by alangibson** [SyncFree/antidote_crdt#25]
Do you have any plans to support any sequence CRDTs like LSEQ or KSEQ?

(Sorry for posting a question here; I couldn't find a reference to a mailing list)

**Comment by bieniusa** [comment]
Thanks for getting in contact!

This seems an excellent idea - we have been focusing on other issues recently, but if there is interest we certainly open to look at collaborative editing use cases.
One of our students implemented a prototype for a sequence CRDT, but this implementation has a some performance issues. We therefore didn't put it on Master here.

Would you be interested in contributing?

**Comment by albsch** [comment]
Please reopen if still valid at https://github.com/AntidoteDB/antidote
